/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author najam
 */
// view list of jobs as office manager and interact with data
public class CurrentJobManagerForm extends javax.swing.JFrame {
Connection conn = null;
PreparedStatement pst = null;
ResultSet rs = null;
    /**
     * Creates new form CurrentJobManagerForm
     */
    public CurrentJobManagerForm() {
        initComponents(); // initialise components
        JobTable(); // dispaly jtable with data provided
        showDate(); // show date
        showTime(); // show time
    }
    
    void showDate() {
        java.util.Date d = new java.util.Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        label_date.setText(s.format(d));
    }

    void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                java.util.Date d = new java.util.Date();
                SimpleDateFormat s = new SimpleDateFormat("hh-mm-ss a");
                label_time.setText(s.format(d));
            }

        }
        ).start();
    }
    
    public void JobTable() {
        try
        {
            // connect to database
            conn = MysqlConnect.ConnectDB();
            // get a list of jobs
            pst =conn.prepareStatement("SELECT job_id AS ID, deadline, complete, priority, quantity, job_description AS 'job description', special_instructions AS 'special instructions', time_completed AS 'time completed', "
                    + "time_created AS 'time created' "
                    + "FROM job ");
            // execute query
            rs = pst.executeQuery();
            // set model to display the list of jobs 
            table_job.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_home = new javax.swing.JButton();
        btn_staff_accounts = new javax.swing.JButton();
        btn_current_jobs = new javax.swing.JButton();
        btn_late_payments = new javax.swing.JButton();
        btn_reminder = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btm_enquiries = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        btn_jobComplete = new javax.swing.JButton();
        btn_tasks = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_job = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        label_date = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        label_time = new javax.swing.JLabel();
        btn_refresh = new javax.swing.JButton();
        Priority = new javax.swing.JCheckBox();
        Deadline = new javax.swing.JCheckBox();
        Completed = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        btn_home.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btn_home.setText("Home");
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });

        btn_staff_accounts.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btn_staff_accounts.setText("Staff Accounts");
        btn_staff_accounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_staff_accountsActionPerformed(evt);
            }
        });

        btn_current_jobs.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btn_current_jobs.setText("Current Jobs");
        btn_current_jobs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_current_jobsActionPerformed(evt);
            }
        });

        btn_late_payments.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btn_late_payments.setText("Late Payments");
        btn_late_payments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_late_paymentsActionPerformed(evt);
            }
        });

        btn_reminder.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btn_reminder.setText("Reminder");
        btn_reminder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reminderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btn_staff_accounts)
                .addGap(35, 35, 35)
                .addComponent(btn_current_jobs)
                .addGap(18, 18, 18)
                .addComponent(btn_late_payments)
                .addGap(26, 26, 26)
                .addComponent(btn_reminder)
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_home, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_current_jobs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(btn_staff_accounts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_late_payments, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_reminder, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        btm_enquiries.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btm_enquiries.setText("View Enquiries");
        btm_enquiries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_enquiriesActionPerformed(evt);
            }
        });

        btn_logout.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btn_logout.setText("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        btn_jobComplete.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btn_jobComplete.setText("Mark Job Complete");
        btn_jobComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jobCompleteActionPerformed(evt);
            }
        });

        btn_tasks.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btn_tasks.setText("Check Tasks");
        btn_tasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tasksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btm_enquiries)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_tasks, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_jobComplete, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btm_enquiries)
                    .addComponent(btn_logout)
                    .addComponent(btn_tasks)
                    .addComponent(btn_jobComplete))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("Search:");

        txt_search.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });

        btn_search.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        jScrollPane3.setBackground(new java.awt.Color(51, 51, 51));

        table_job.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Job ID", "Priority", "Deadline", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(table_job);

        label_date.setText("ID");

        jLabel9.setText("Name");

        label_time.setText("Date");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(label_date)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(288, 288, 288)
                .addComponent(label_time)
                .addGap(64, 64, 64))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_date)
                    .addComponent(jLabel9)
                    .addComponent(label_time))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_refresh.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btn_refresh.setText("Refresh Table");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        Priority.setText("Priority");
        Priority.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriorityActionPerformed(evt);
            }
        });

        Deadline.setText("Deadline");
        Deadline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeadlineActionPerformed(evt);
            }
        });

        Completed.setText("Completed");
        Completed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompletedActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setText("Filter:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Priority)
                        .addGap(18, 18, 18)
                        .addComponent(Deadline)
                        .addGap(18, 18, 18)
                        .addComponent(Completed)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txt_search))
                .addGap(18, 18, 18)
                .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Priority)
                    .addComponent(Deadline)
                    .addComponent(Completed)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel7.setText("Bloomsbury Image Processing Laboratory");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 626, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_current_jobsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_current_jobsActionPerformed
        // TODO add your handling code here:
        CurrentJobManagerForm cjmf = new CurrentJobManagerForm();
        cjmf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_current_jobsActionPerformed

    private void btn_late_paymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_late_paymentsActionPerformed
        // TODO add your handling code here:
        LatePaymentForm lpf = new LatePaymentForm();
        lpf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_late_paymentsActionPerformed

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        
    }//GEN-LAST:event_txt_searchActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        try
        {
            // connect to database
            conn = MysqlConnect.ConnectDB();
            // list jobs where customer id matches the value in the text field
            pst =conn.prepareStatement("SELECT job_id AS ID, deadline, complete, priority, quantity, job_description AS 'job description', special_instructions AS 'special instructions', time_completed AS 'time completed', "
                    + "time_created AS 'time created' "
                    + "FROM job "
                    + "WHERE customer_customer_id = '"+txt_search.getText()+"'");
            //execute query
            rs = pst.executeQuery();
            table_job.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:
        JobTable(); // show data from job table method
        txt_search.setText(""); // set search text field to null
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btm_enquiriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_enquiriesActionPerformed
        // TODO add your handling code here:
        ViewEnquiriesForm vef = new ViewEnquiriesForm();
        vef.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btm_enquiriesActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        LoginPageForm lpf = new LoginPageForm();
        lpf.setVisible(true);
        this.dispose();
        // pop up message
        JOptionPane.showMessageDialog(null, "You have successfully been logged out");
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        // TODO add your handling code here:
        OfficeManagerHomeForm omhf = new OfficeManagerHomeForm();
        omhf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_staff_accountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_staff_accountsActionPerformed
        // TODO add your handling code here:
        StaffAccountOfficeManagerForm saof = new StaffAccountOfficeManagerForm();
        saof.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_staff_accountsActionPerformed

    private void btn_reminderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reminderActionPerformed
        // TODO add your handling code here:
        ReminderForm rf = new ReminderForm();
        rf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_reminderActionPerformed

    private void PriorityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriorityActionPerformed
        try
        {
            // if checkbox is checked
            if (Priority.isSelected()) {
                conn = MysqlConnect.ConnectDB();
                // sql statement to filter table based on priority in ascending order
                pst =conn.prepareStatement("SELECT job_id AS ID, deadline, complete, priority, quantity, job_description AS 'job description', special_instructions AS 'special instructions', time_completed AS 'time completed', "
                    + "time_created AS 'time created' "
                    + "FROM job "
                        + "ORDER BY priority ASC");
                rs = pst.executeQuery();
                table_job.setModel(DbUtils.resultSetToTableModel(rs));
            } else {
                // if ot checked, jobtable() method is called
                JobTable();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_PriorityActionPerformed

    private void DeadlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeadlineActionPerformed
        // TODO add your handling code here:
        try
        {
            // if deadline checkbo is checked perform query
            if (Deadline.isSelected()) {
                // make conection to sql
                conn = MysqlConnect.ConnectDB();
                // filter table based on deadline i ascending order
                pst =conn.prepareStatement("SELECT job_id AS ID, deadline, complete, priority, quantity, job_description AS 'job description', special_instructions AS 'special instructions', time_completed AS 'time completed', "
                    + "time_created AS 'time created' "
                    + "FROM job "
                        + "ORDER BY deadline ASC");
                rs = pst.executeQuery();
                table_job.setModel(DbUtils.resultSetToTableModel(rs));
            } else {
                // if not checked, jobtable is called
                JobTable();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_DeadlineActionPerformed

    private void CompletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompletedActionPerformed
        // TODO add your handling code here:
        try
        {
            // if completed checkbox is checked, perform task
            if (Completed.isSelected()) {
                // make connection to database
                conn = MysqlConnect.ConnectDB();
                
                pst =conn.prepareStatement("SELECT job_id AS ID, deadline, complete, priority, quantity, job_description AS 'job description', special_instructions AS 'special instructions', time_completed AS 'time completed', "
                    + "time_created AS 'time created' "
                    + "FROM job "
                        + "WHERE complete = 1");
                rs = pst.executeQuery();
                table_job.setModel(DbUtils.resultSetToTableModel(rs));
            } else {
                JobTable();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CompletedActionPerformed

    private void btn_jobCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jobCompleteActionPerformed
        // set integer type row to the selected row
        int row = table_job.getSelectedRow();
        // 
        DefaultTableModel model = (DefaultTableModel)table_job.getModel();
        // set string variabled selected to value of item in the first row - set this value to a string
        String selected = model.getValueAt(row, 0).toString();
        // set local to the current time
        LocalDateTime local = LocalDateTime.now();
        // if row is selected
        if (row >= 0) {
            // update the complete and time_completed attribute where job_id equals the value of the id selected
            try {
                conn = MysqlConnect.ConnectDB();
                pst = conn.prepareStatement("UPDATE job SET complete = 1, time_completed = '"+local.toString()+"' WHERE job_id = '"+ selected +"' ");
                pst.executeUpdate();
                JobTable();
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_btn_jobCompleteActionPerformed

    private void btn_tasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tasksActionPerformed
        OfficeCurrentTaskForm ch = new OfficeCurrentTaskForm();

        int index = table_job.getSelectedRow();
        TableModel model = table_job.getModel();
        // get value of item on first row and set it to id
        String id = model.getValueAt(index, 0).toString();

        ch.setVisible(true);
        // cause window to be sized to fir preffered size of layout of its sub components
        ch.pack();
        this.dispose();
        // set text field in next jframe to value of the selected field in the tablew
        ch.txt_jobID.setText(id);
    }//GEN-LAST:event_btn_tasksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrentJobManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrentJobManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrentJobManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrentJobManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CurrentJobManagerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Completed;
    private javax.swing.JCheckBox Deadline;
    private javax.swing.JCheckBox Priority;
    private javax.swing.JButton btm_enquiries;
    private javax.swing.JButton btn_current_jobs;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_jobComplete;
    private javax.swing.JButton btn_late_payments;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_reminder;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_staff_accounts;
    private javax.swing.JButton btn_tasks;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel label_date;
    private javax.swing.JLabel label_time;
    private javax.swing.JTable table_job;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
